const sr = ScrollReveal({reset: true})

ScrollReveal().reveal('.distintivostopo', { delay: 350 }, { distance: '80px' }, { origin: 'left' })
ScrollReveal().reveal('.ciclotitulo1', { delay: 550 }, { distance: '80px' }, { origin: 'left' })
ScrollReveal().reveal('.ciclotitulo2', { delay: 750 }, { distance: '80px' }, { origin: 'left' })
ScrollReveal().reveal('.ciclotitulo3', { delay: 1050 }, { distance: '80px' }, { origin: 'left' })
ScrollReveal().reveal('.ciclosubtitulo', { delay: 1750 }, { distance: '80px' }, { origin: 'left' })
ScrollReveal().reveal('.menu1', { delay: 2050 }, { distance: '80px' }, { origin: 'left' })
ScrollReveal().reveal('.linhadivisoriabody', { delay: 50 }, { distance: '80px' })
ScrollReveal().reveal('.sobre', { delay: 350 }, { distance: '10px' })
ScrollReveal().reveal('.sobre-logo-ciclo', { delay: 250 }, { distance: '8px' })
ScrollReveal().reveal('.sobre-logo-imm', { delay: 750 }, { distance: '8px' })
ScrollReveal().reveal('.sobre-logo-eceme', { delay: 750 }, { distance: '8px' })
ScrollReveal().reveal('.linhadivisoriatexto', { delay: 550 }, { distance: '80px' })
ScrollReveal().reveal('.h1-sobre', { delay: 250 }, { distance: '80px' })
ScrollReveal().reveal('.h2-sobre', { delay: 250 }, { distance: '80px' })
ScrollReveal().reveal('.h3-sobre', { delay: 250 }, { distance: '80px' })
ScrollReveal().reveal('.menu2', { delay: 550 }, { distance: '80px' }, { origin: 'left' })
ScrollReveal().reveal('.sobre-conteudo', { delay: 550 }, { distance: '80px' })
ScrollReveal().reveal('.sobre-inline', { delay: 550 }, { distance: '80px' })
ScrollReveal().reveal('.sobre-duplo', { delay: 550 }, { distance: '80px' })
ScrollReveal().reveal('.sobre-logos-apoio-pessoas-3-colunas', { delay: 550 }, { distance: '80px' })
ScrollReveal().reveal('.sobre-logos-apoio-pessoas-4-colunas', { delay: 550 }, { distance: '80px' })
ScrollReveal().reveal('.btn-voltarcima', { delay: 550 }, { distance: '80px' })

