const sr = ScrollReveal({reset: true})

ScrollReveal().reveal('.distintivostopo', { delay: 350 }, { distance: '80px' }, { origin: 'left' })
ScrollReveal().reveal('.container-titulos', { delay: 550 }, { distance: '80px' }, { origin: 'left' })
ScrollReveal().reveal('.container-titulos2', { delay: 750 }, { distance: '80px' }, { origin: 'left' })
ScrollReveal().reveal('.container-titulos3', { delay: 1050 }, { distance: '80px' }, { origin: 'left' })
ScrollReveal().reveal('.container-subtitulo', { delay: 1750 }, { distance: '80px' }, { origin: 'left' })
ScrollReveal().reveal('.btn-geral', { delay: 2050 }, { distance: '80px' }, { origin: 'left' })
ScrollReveal().reveal('.linhadivisoriabody', { delay: 50 }, { distance: '80px' })
ScrollReveal().reveal('.sobre', { delay: 650 }, { distance: '2px' })
ScrollReveal().reveal('.sobre-o-ciclo', { delay: 450 }, { distance: '8px' })
ScrollReveal().reveal('.sobre-logo-ciclo', { delay: 250 }, { distance: '1px' })
ScrollReveal().reveal('.sobre-logo-imm', { delay: 550 }, { distance: '8px' })
ScrollReveal().reveal('.sobre-logo-eceme', { delay: 550 }, { distance: '8px' })
ScrollReveal().reveal('.linhadivisoriatexto', { delay: 550 }, { distance: '80px' })
ScrollReveal().reveal('.h1-sobre', { delay: 550 }, { distance: '80px' })
ScrollReveal().reveal('.h2-sobre', { delay: 550 }, { distance: '80px' })
ScrollReveal().reveal('.h3-sobre', { delay: 550 }, { distance: '80px' })
ScrollReveal().reveal('.menu3', { delay: 650 }, { distance: '80px' }, { origin: 'left' })
ScrollReveal().reveal('.sobre-conteudo', { delay: 550 }, { distance: '80px' })
ScrollReveal().reveal('.sobre-inline', { delay: 650 }, { distance: '80px' })
ScrollReveal().reveal('.sobre-duplo', { delay: 550 }, { distance: '80px' })
ScrollReveal().reveal('.sobre-logos-apoio-pessoas-3-colunas', { delay: 550 }, { distance: '80px' })
ScrollReveal().reveal('.sobre-logos-apoio-pessoas-4-colunas', { delay: 550 }, { distance: '80px' })
ScrollReveal().reveal('.footer', { delay: 950 }, { distance: '80px' })
ScrollReveal().reveal('.btn-voltarcima', { delay: 550 }, { distance: '80px' })

